package tlw

type TailwindClass string

const (
	Container         TailwindClass = "container"
	BoxBorder         TailwindClass = "box-border"
	BoxContent        TailwindClass = "box-content"
	Block             TailwindClass = "block"
	InlineBlock       TailwindClass = "inline-block"
	Inline            TailwindClass = "inline"
	Flex              TailwindClass = "flex"
	InlineFlex        TailwindClass = "inline-flex"
	Grid              TailwindClass = "grid"
	InlineGrid        TailwindClass = "inline-grid"
	Table             TailwindClass = "table"
	TableCaption      TailwindClass = "table-caption"
	TableCell         TailwindClass = "table-cell"
	TableColumn       TailwindClass = "table-column"
	TableColumnGroup  TailwindClass = "table-column-group"
	TableFooter       TailwindClass = "table-footer"
	TableHeader       TailwindClass = "table-header"
	TableRowGroup     TailwindClass = "table-row-group"
	TableRow          TailwindClass = "table-row"
	Hidden            TailwindClass = "hidden"
	Clearfix          TailwindClass = "clearfix"
	FloatRight        TailwindClass = "float-right"
	FloatLeft         TailwindClass = "float-left"
	FloatNone         TailwindClass = "float-none"
	ObjectContain     TailwindClass = "object-contain"
	ObjectCover       TailwindClass = "object-cover"
	ObjectFill        TailwindClass = "object-fill"
	ObjectNone        TailwindClass = "object-none"
	ObjectScaleDown   TailwindClass = "object-scale-down"
	ObjectBottom      TailwindClass = "object-bottom"
	ObjectCenter      TailwindClass = "object-center"
	ObjectLeft        TailwindClass = "object-left"
	ObjectLeftBottom  TailwindClass = "object-left-bottom"
	ObjectLeftTop     TailwindClass = "object-left-top"
	ObjectRight       TailwindClass = "object-right"
	ObjectRightBottom TailwindClass = "object-right-bottom"
	ObjectRightTop    TailwindClass = "object-right-top"
	ObjectTop         TailwindClass = "object-top"
)
