package tlw

const (
	MaxWNone TailwindClass = "max-w-none"
	MaxWXs   TailwindClass = "max-w-xs"
	MaxWSm   TailwindClass = "max-w-sm"
	MaxWMd   TailwindClass = "max-w-md"
	MaxWLg   TailwindClass = "max-w-lg"
	MaxWXl   TailwindClass = "max-w-xl"
	MaxW2Xl  TailwindClass = "max-w-2xl"
	MaxW3Xl  TailwindClass = "max-w-3xl"
	MaxW4Xl  TailwindClass = "max-w-4xl"
	MaxW5Xl  TailwindClass = "max-w-5xl"
	MaxW6Xl  TailwindClass = "max-w-6xl"
	MaxWFull TailwindClass = "max-w-full"

	WFull TailwindClass = "w-full"
	W1    TailwindClass = "w-1"
	W2    TailwindClass = "w-2"
	W3    TailwindClass = "w-3"
	W4    TailwindClass = "w-4"
	W5    TailwindClass = "w-5"
	W6    TailwindClass = "w-6"
	W8    TailwindClass = "w-8"
	W10   TailwindClass = "w-10"
	W12   TailwindClass = "w-12"
	W16   TailwindClass = "w-16"
	W20   TailwindClass = "w-20"
	W24   TailwindClass = "w-24"
	W32   TailwindClass = "w-32"
	W40   TailwindClass = "w-40"
	W48   TailwindClass = "w-48"
	W56   TailwindClass = "w-56"
	W64   TailwindClass = "w-64"
	WAuto TailwindClass = "w-auto"

	W1_2     TailwindClass = "w-1/2"
	W1_3     TailwindClass = "w-1/3"
	W2_3     TailwindClass = "w-2/3"
	W1_4     TailwindClass = "w-1/4"
	W3_4     TailwindClass = "w-3/4"
	W1_5     TailwindClass = "w-1/5"
	W2_5     TailwindClass = "w-2/5"
	W3_5     TailwindClass = "w-3/5"
	W4_5     TailwindClass = "w-4/5"
	W1_6     TailwindClass = "w-1/6"
	W5_6     TailwindClass = "w-5/6"
	W1_12    TailwindClass = "w-1/12"
	W5_12    TailwindClass = "w-5/12"
	W7_12    TailwindClass = "w-7/12"
	W9_12    TailwindClass = "w-9/12"
	W11_12   TailwindClass = "w-11/12"
	FlexGrow TailwindClass = "flex-grow"

	// Min-Width fractions
	MinW0    TailwindClass = "min-w-0"
	MinWFull TailwindClass = "min-w-full"
	MinW1_2  TailwindClass = "min-w-1/2"
	MinW1_3  TailwindClass = "min-w-1/3"
	MinW2_3  TailwindClass = "min-w-2/3"
	MinW1_4  TailwindClass = "min-w-1/4"
	MinW3_4  TailwindClass = "min-w-3/4"
)
